[tools]
# 言語とインフラ
node = "latest"
terraform = "latest"
tflint = "latest"
uv = "latest"
# CLI ツール
awscli = "latest"
bat = "latest"
chezmoi = "latest"
ctop = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
neovim = "latest"
ripgrep = "latest"
sheldon = "latest"
starship = "latest"
usage = "latest"
yazi = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = []
windows_shim_mode = "hardlink"
